### ISSUE TITLE
error using ONNXHelper

### ISSUE THREAD

**Issue by GammaLyra** [t-wolfeadam/AnyLogic-ONNX-Helper#9]
Hi,

I have created an ONNX model with Python (a neural network trained with Tensorflow and Keras), and I am tring to use ONNXHelper for using this neural network in Anylogic. But when execute the simulation I obtain this error:

_Could not initialize class onnx_wrapper.OnnxHelper_
 
In more detail:

<img width="509" alt="error" src="https://github.com/t-wolfeadam/AnyLogic-ONNX-Helper/assets/96059492/9270f0e6-7356-4ba5-9b5b-ddfc8b2ac58a">

I configurate teh ONNXhelper like that:

<img width="445" alt="onnx_helper" src="https://github.com/t-wolfeadam/AnyLogic-ONNX-Helper/assets/96059492/a05478a3-8d58-4c64-80a1-20faa9ab0bef">

Am I doing something wrong?

Thanks for everything!

Belén Arroyo

**Comment by t-wolfeadam** [comment]
Hi, so for your first problem, dyk what version you were on previously? Just useful info for my reference.

Also, in the second problem, the class it's looking for (`red_neuronal.Simulation`) is referring to the Simulation experiment of your current model (assuming it's named something like "Red Neuronal"). My guess is that it's some obscure AL issue from updating? Try closing your model, then restarting AL, and relaunching the experiment.

**Comment by GammaLyra** [comment]
Hi,

I used the version of Anylogic 8.8.1. I did the steps that you explain there:

https://github.com/t-wolfeadam/AnyLogic-ONNX-Helper/wiki/Technical-Details#re-exporting-the-library

But it still didn't work. Finally, I upgrade my version of Anylogic, now I have the version 8.8.4.20.2307181708. I add again the ONNXLibrary that you have in your git, and now I obtain this error:

<img width="446" alt="error3" src="https://github.com/t-wolfeadam/AnyLogic-ONNX-Helper/assets/96059492/f98a5e21-362e-428d-a009-e8d1426f2298">

Could the problem be in the way I have converted my trained model to ONNX format in Python? I use this command:

_from tf2onnx.keras2onnx_api import convert_keras
proto = convert_keras(model)
onnx.save(proto, "test.onnx")_

Thanks for everything!

Best regards,
Belén

**Comment by GammaLyra** [comment]
Hi, 

I solved the problem. I was exporting the model to the ONNX file from Python incorrectly. Now the problem is that the result I get for the prediction is different that the prediction I obtain with Python. Is the order of the input variables the same as you use when train the model?

I attach the model, the simulation in Anylogic and the Python script where I make the prediction.

[test.zip](https://github.com/t-wolfeadam/AnyLogic-ONNX-Helper/files/12765377/test.zip)

Thanks for everything!

Best regards,
Belén

**Comment by t-wolfeadam** [comment]
Hi! So I was unable to load your pkl file - it appears issues in my version of keras (v2.7.0, Py3.9) likely being different from yours. However, I was able to load the onnx file and it shows the same results both in Python and AL. 

![image](https://github.com/t-wolfeadam/AnyLogic-ONNX-Helper/assets/40703071/2655d140-d584-490c-98a8-f7a28a92e285)

My guess is that it's something in the conversion to ONNX that's lost or incomplete. I'm closing as it's not an issue related to the ONNX lib, but feel free to LMK if you have any other Qs. You can also try using my [Pypeline library](https://github.com/t-wolfeadam/AnyLogic-Pypeline?) to load and query the pkl file that way, thus allowing you to use the unconverted format.
